- name: installation masternode BaisycCoin
  hosts: installBaisycCoin
  become: False
  vars:
          baisyccoin_cli: files/baisyccoin-1.0.0/bin/baisyccoin-cli
          baisyccoind: files/baisyccoin-1.0.0/bin/baisyccoind
          password: "{{ 999999999999 | random | to_uuid | password_hash('sha512') }}"
          rpcpassword: "{{ 999999999999 | random | to_uuid }}"
          rpcport: 64759
          mnport: 64758
          ansible_ssh_user: root
  tasks:
          - name: create user baisyccoin
            user:
                    name: baisyccoin
                    state: present
                    update_password: on_create
                    password: "{{ password }}"
                    shell: /bin/bash

          - name: suppress password for user baisyccoin
            lineinfile:
                    dest: /etc/shadow
                    regexp: '^baisyccoin:'
                    line: 'baisyccoin:*:17670:0:99999:7:::'
                    validate: pwck -rq %s

          - name: copy baisyccoin utils
            copy:
                    src='{{ item.src }}'
                    dest='/usr/local/bin/{{ item.dest }}'
                    mode=0755
                    owner=root
                    group=root
            with_items:
                    - { src: '{{ baisyccoin_cli }}', dest: 'baisyccoin-cli' }
                    - { src: '{{ baisyccoind }}', dest: 'baisyccoind' }

          - name: create .baisyccoin directory
            file: path=/home/BaisycCoin/.baisyccoin state=directory owner=BaisycCoin group=BaisycCoin mode=0750

          - name: create baisyccoin.conf
            template:
                    src: templates/mn.conf.j2
                    dest: /home/BaisycCoin/.baisyccoin/baisyccoin.conf
                    owner: BaisycCoin
                    group: BaisycCoin
                    mode: 0640
          
          - name: start baisyccoind
            command: /usr/local/bin/baisyccoind -daemon
            become: yes
            become_user: baisyccoin

          - name: modify masternode.conf
            lineinfile:
                    # dest should be changed to path from 2.3 onward
                    dest: /home/baisyccoin/.baisyccoin/masternode.conf
                    regexp: '^{{ inventory_hostname }}'
                    line: '{{ inventory_hostname }} {{ ansible_ssh_host }}:{{ mnport }} {{masternode_priv_key }} {{ masternode_tx }} {{ masternode_index }}'

          - name: add a cronjob to restart baisyccoind on reboot
            cron:
                    name: "starts baisyccoind on reboot"
                    special_time: reboot
                    job: "sleep 60 && /usr/local/bin/baisyccoind -daemon"
                    user: baisyccoin
